name = "aoc_day10"
version = "0.1.0"
defaultTargets = ["aoc_day10_p1", "aoc_day10_p2"]

[[lean_lib]]
name = "AocDay10"

[[lean_exe]]
name = "aoc_day10_p1"
root = "P1"

[[lean_exe]]
name = "aoc_day10_p2"
root = "P2"
