name = "aoc_day16"
version = "0.1.0"
defaultTargets = ["aoc_day16_p1", "aoc_day16_p2"]

[[lean_lib]]
name = "AocDay16"

[[lean_exe]]
name = "aoc_day16_p1"
root = "P1"

[[lean_exe]]
name = "aoc_day16_p2"
root = "P2"
