name = "aoc_day22"
version = "0.1.0"
defaultTargets = ["aoc_day22_p1", "aoc_day22_p2"]

[[lean_lib]]
name = "AocDay22"

[[lean_exe]]
name = "aoc_day22_p1"
root = "P1"

[[lean_exe]]
name = "aoc_day22_p2"
root = "P2"
