name = "aoc_day21"
version = "0.1.0"
defaultTargets = ["aoc_day21_p1", "aoc_day21_p2"]

[[lean_lib]]
name = "AocDay21"

[[lean_exe]]
name = "aoc_day21_p1"
root = "P1"

[[lean_exe]]
name = "aoc_day21_p2"
root = "P2"
