name = "aoc_day18"
version = "0.1.0"
defaultTargets = ["aoc_day18_p1", "aoc_day18_p2"]

[[lean_lib]]
name = "AocDay18"

[[lean_exe]]
name = "aoc_day18_p1"
root = "P1"

[[lean_exe]]
name = "aoc_day18_p2"
root = "P2"
