name = "aoc_day1_p1"
version = "0.1.0"
defaultTargets = ["aoc_day1_p1"]

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.14.0-rc1"

[[lean_lib]]
name = "AocDay1P1"

[[lean_exe]]
name = "aoc_day1_p1"
root = "P1"

[[lean_exe]]
name = "aoc_day1_p2"
root = "P2"


