name = "aoc_day14"
version = "0.1.0"
defaultTargets = ["aoc_day14_p1", "aoc_day14_p2"]

[[lean_lib]]
name = "AocDay14"

[[lean_exe]]
name = "aoc_day14_p1"
root = "P1"

[[lean_exe]]
name = "aoc_day14_p2"
root = "P2"
