name = "aoc_day20"
version = "0.1.0"
defaultTargets = ["aoc_day20_p1", "aoc_day20_p2"]

[[lean_lib]]
name = "AocDay20"

[[lean_exe]]
name = "aoc_day20_p1"
root = "P1"

[[lean_exe]]
name = "aoc_day20_p2"
root = "P2"
