name = "aoc_day11"
version = "0.1.0"
defaultTargets = ["aoc_day11_p1", "aoc_day11_p2"]

[[lean_lib]]
name = "AocDay11"

[[lean_exe]]
name = "aoc_day11_p1"
root = "P1"

[[lean_exe]]
name = "aoc_day11_p2"
root = "P2"
