name = "aoc_day23"
version = "0.1.0"
defaultTargets = ["aoc_day23_p1", "aoc_day23_p2"]

[[lean_lib]]
name = "AocDay23"

[[lean_exe]]
name = "aoc_day23_p1"
root = "P1"

[[lean_exe]]
name = "aoc_day23_p2"
root = "P2"
