name = "aoc_day3"
version = "0.1.0"
defaultTargets = ["aoc_day3_p1", "aoc_day3_p2"]

[[lean_lib]]
name = "AocDay3"

[[lean_exe]]
name = "aoc_day3_p1"
root = "P1"

[[lean_exe]]
name = "aoc_day3_p2"
root = "P2"