name = "aoc_day9"
version = "0.1.0"
defaultTargets = ["aoc_day9_p1", "aoc_day9_p2"]

[[lean_lib]]
name = "AocDay9"

[[lean_exe]]
name = "aoc_day9_p1"
root = "P1"

[[lean_exe]]
name = "aoc_day9_p2"
root = "P2"
