name = "aoc_day15"
version = "0.1.0"
defaultTargets = ["aoc_day15_p1", "aoc_day15_p2"]

[[lean_lib]]
name = "AocDay15"

[[lean_exe]]
name = "aoc_day15_p1"
root = "P1"

[[lean_exe]]
name = "aoc_day15_p2"
root = "P2"
